from django.urls import path
from . import views

urlpatterns = [
    path('connections/', views.connection_list),
    path('connections/<str:pk>/', views.connection_detail),
    path('test/', views.test_connection),
    path('test/<str:pk>/', views.test_saved_connection),
    path('<str:pk>/structure/', views.get_structure),
    path('<str:pk>/query/', views.execute_query),
    path('instances/', views.instance_list),
    path('instances/<int:pk>/', views.instance_detail),
    path('instances/<int:pk>/test/', views.instance_test),
    path('instances/<int:pk>/schema/', views.instance_schema),
    path('instances/<int:pk>/table-detail/', views.instance_table_detail),
    path('instances/<int:pk>/diagnostics/', views.instance_diagnostics),
    path('sql/format/', views.sql_format),
    path('sql/completion/', views.sql_completion),
    path('sql/explain/', views.sql_explain),
    path('sql/ai-review/', views.sql_ai_review),
    path('sql/jobs/', views.sql_job_list),
    path('sql/jobs/create/', views.sql_job_create),
    path('sql/jobs/<int:pk>/', views.sql_job_detail),
    path('sql/jobs/<int:pk>/logs/', views.sql_job_logs),
    path('sql/jobs/<int:pk>/result/', views.sql_job_result),
    path('sql/jobs/<int:pk>/cancel/', views.sql_job_cancel),
    path('sql/jobs/<int:pk>/pause/', views.sql_job_pause),
    path('sql/jobs/<int:pk>/resume/', views.sql_job_resume),
    path('approvals/', views.approval_list),
    path('approvals/<int:pk>/', views.approval_detail),
    path('approvals/<int:pk>/approve/', views.approval_approve),
    path('approvals/<int:pk>/reject/', views.approval_reject),
    path('approval-policies/', views.approval_policy_list),
    path('approval-policies/<int:pk>/', views.approval_policy_detail),
    path('access-rules/', views.access_rule_list),
    path('access-rules/<int:pk>/', views.access_rule_detail),
    path('audit/logs/', views.audit_list),
    path('audit/logs/<int:pk>/', views.audit_detail),
    path('audit/export/', views.audit_export),
    path('backup/plans/', views.backup_plan_list),
    path('backup/plans/<int:pk>/', views.backup_plan_detail),
    path('backup/plans/<int:pk>/run/', views.backup_plan_run),
    path('backup/records/', views.backup_record_list),
    path('restore/jobs/', views.restore_job_list),
    path('rollback/jobs/', views.rollback_job_list),
    path('rollback/jobs/<int:pk>/execute/', views.rollback_job_execute),
]
