# Generated by Django 4.2.11 on 2026-01-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
