# Generated by Django 4.2.11 on 2026-03-30 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_manager', '0004_backupplan_backuprecord_sqlapprovalpolicy_restorejob'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('group_name', models.CharField(blank=True, default='', max_length=150)),
                ('database_pattern', models.CharField(blank=True, default='*', max_length=128)),
                ('table_pattern', models.CharField(blank=True, default='*', max_length=128)),
                ('sql_types', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='db_manager.dbinstance')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_access_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
