# Generated by Django 4.2.11 on 2026-03-30 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_manager', '0005_dbaccessrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollbackJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_txn_id', models.CharField(blank=True, default='', max_length=128)),
                ('rollback_sql', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('approved', 'Approved'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('log_json', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rollback_jobs', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollback_jobs', to='db_manager.dbinstance')),
                ('source_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollback_jobs', to='db_manager.sqlauditlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
