# Generated by Django 4.2.11 on 2026-03-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0006_rollbackjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupplan',
            name='compression_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='backupplan',
            name='encryption_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backupplan',
            name='storage_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='checksum_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='trace_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='restorejob',
            name='trace_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='rollbackjob',
            name='trace_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sqlapprovalpolicy',
            name='approval_flow',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sqlapprovalpolicy',
            name='sla_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='sqlauditlog',
            name='after_image_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sqlauditlog',
            name='before_image_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sqlauditlog',
            name='txn_snapshot_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sqlexecutionjob',
            name='trace_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
