# Generated by Django 4.2.11 on 2026-03-31 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0007_backupplan_compression_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLExecutionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('priority', models.IntegerField(default=100)),
                ('environment_scope', models.JSONField(blank=True, default=list)),
                ('db_type_scope', models.JSONField(blank=True, default=list)),
                ('sql_type_scope', models.JSONField(blank=True, default=list)),
                ('risk_scope', models.JSONField(blank=True, default=list)),
                ('database_pattern', models.CharField(blank=True, default='*', max_length=128)),
                ('auto_execute_mode', models.CharField(choices=[('auto_commit', 'Auto Commit'), ('transaction', 'Transaction'), ('dry_run', 'Dry Run')], default='auto_commit', max_length=32)),
                ('require_approval', models.BooleanField(default=False)),
                ('allow_direct_execute', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', '-updated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sqlapprovalorder',
            name='cc_users_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sqlapprovalorder',
            name='request_payload_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sqlapprovalorder',
            name='requested_flow_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
