# Generated by Django 4.2.11 on 2026-01-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_monitorconfig_s3_archive_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Monitor', max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('k8s_namespace', models.CharField(default='default', help_text='K8s Namespace to watch', max_length=255)),
                ('k8s_kubeconfig', models.TextField(blank=True, help_text='Kubeconfig content (YAML). If empty, use in-cluster config or default.', null=True)),
                ('s3_archive_enabled', models.BooleanField(default=False, help_text='Enable archiving logs to S3')),
                ('s3_bucket', models.CharField(blank=True, max_length=255, null=True)),
                ('s3_region', models.CharField(default='us-east-1', max_length=50)),
                ('s3_access_key', models.CharField(blank=True, max_length=255, null=True)),
                ('s3_secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('s3_endpoint', models.CharField(blank=True, help_text='Optional custom endpoint', max_length=255, null=True)),
                ('retention_days', models.IntegerField(default=3, help_text='Days to keep logs locally before S3 upload')),
                ('slack_webhook_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('poll_interval_seconds', models.IntegerField(default=60)),
                ('alert_keywords', models.JSONField(default=list)),
                ('ignore_keywords', models.JSONField(default=list)),
                ('record_only_keywords', models.JSONField(default=list)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('alerts_sent_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='MonitorConfig',
        ),
    ]
