# Generated by Django 4.2.11 on 2026-01-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_monitortask_delete_monitorconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortask',
            name='alert_enabled',
            field=models.BooleanField(default=True, help_text='Global switch to enable/disable alert sending'),
        ),
    ]
