# Generated by Django 4.2.11 on 2026-01-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_monitortask_alert_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortask',
            name='alert_threshold_count',
            field=models.IntegerField(default=5, help_text='Count of errors to trigger alert'),
        ),
        migrations.AddField(
            model_name='monitortask',
            name='alert_threshold_window',
            field=models.IntegerField(default=60, help_text='Window in seconds for threshold counting'),
        ),
        migrations.AddField(
            model_name='monitortask',
            name='immediate_keywords',
            field=models.JSONField(default=list, help_text='Immediate Alert: Alert on first occurrence'),
        ),
        migrations.AlterField(
            model_name='monitortask',
            name='alert_keywords',
            field=models.JSONField(default=list, help_text='Threshold Alert: Error > Threshold in Window'),
        ),
        migrations.AlterField(
            model_name='monitortask',
            name='ignore_keywords',
            field=models.JSONField(default=list, help_text='Ignore: Do not process or alert'),
        ),
        migrations.AlterField(
            model_name='monitortask',
            name='record_only_keywords',
            field=models.JSONField(default=list, help_text='Record Only: Log but do not alert'),
        ),
    ]
