# Generated by Django 4.2.11 on 2026-01-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_monitortask_alert_threshold_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortask',
            name='alert_silence_minutes',
            field=models.IntegerField(default=60, help_text='Silence duplicate alerts for N minutes'),
        ),
        migrations.AddField(
            model_name='monitortask',
            name='alert_state',
            field=models.JSONField(blank=True, default=dict, help_text='Runtime state for alert silencing'),
        ),
    ]
