# Generated by Django 4.2.11 on 2026-01-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_monitortask_alert_silence_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitortask',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='monitortask',
            name='k8s_namespace',
            field=models.CharField(default='default', help_text='K8s Namespace to watch (comma separated for multiple)', max_length=255),
        ),
    ]
