# Generated by Django 4.2.11 on 2026-01-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_alter_monitortask_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortask',
            name='threshold_state',
            field=models.JSONField(blank=True, default=dict, help_text='Runtime state for threshold counting'),
        ),
    ]
