# Generated by Django 4.2.11 on 2026-01-28 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('resolved', 'Resolved')], default='open', max_length=50)),
                ('started_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('raw_alert_data', models.JSONField(help_text='Raw payload from Prometheus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_cause', models.TextField()),
                ('summary', models.TextField()),
                ('solutions', models.JSONField(default=list, help_text='List of suggested solutions')),
                ('related_metrics', models.JSONField(default=dict, help_text='Metrics data for visualization')),
                ('raw_ai_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='ai_ops.incident')),
            ],
        ),
    ]
