# Generated by Django 4.2.11 on 2026-01-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_ops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisreport',
            name='summary',
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='diagnosis_logs',
            field=models.JSONField(default=list, help_text='Logs from diagnostic commands'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='mitigation',
            field=models.TextField(default='', help_text='Immediate actions to fix'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='phenomenon',
            field=models.TextField(default='', help_text='What happened?'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='prevention',
            field=models.TextField(default='', help_text='Long term prevention'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='refactoring',
            field=models.TextField(default='', help_text='Architectural improvements'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='root_cause',
            field=models.TextField(default='', help_text='Why it happened? Which process/pod?'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='solutions',
            field=models.JSONField(default=list, help_text='List of actionable steps'),
        ),
    ]
