# Generated by Django 4.2.11 on 2026-01-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_ops', '0002_remove_analysisreport_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('deepseek', 'DeepSeek'), ('custom', 'Custom')], default='openai', max_length=50)),
                ('api_base', models.CharField(default='https://api.openai.com/v1', help_text='API Base URL', max_length=255)),
                ('api_key', models.CharField(blank=True, help_text='API Key', max_length=255)),
                ('model', models.CharField(default='gpt-3.5-turbo', max_length=100)),
                ('max_tokens', models.IntegerField(default=2000)),
                ('temperature', models.FloatField(default=0.7)),
                ('prompt_template', models.TextField(default='\n你是一个Kubernetes和系统运维专家。请分析以下告警并以JSON格式输出分析报告。\n请严格使用中文回答。\n\n告警信息: {alert_name}\n原始数据: {raw_data}\n相关指标: {metrics}\n诊断日志: {logs}\n\n请按照以下步骤思考并输出JSON:\n1. phenomenon: 用一句话描述发生了什么故障现象。\n2. root_cause: 根本原因是什么？具体是哪个进程(PID)或Pod导致的？\n3. mitigation: 现在的紧急处理措施是什么？(如 kill 进程, 限流等)\n4. prevention: 未来如何防止复发？(配置修改, 资源限制等)\n5. refactoring: 架构层面如何优化？\n6. solutions: 一个包含具体可执行命令的字符串列表(list of strings)。\n\n输出格式要求:\n{\n    "phenomenon": "...",\n    "root_cause": "...",\n    "mitigation": "...",\n    "prevention": "...",\n    "refactoring": "...",\n    "solutions": ["cmd1", "cmd2"]\n}\n')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
