# Generated by Django 4.2.11 on 2026-01-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_ops', '0003_aiconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='fingerprint',
            field=models.CharField(db_index=True, default='', help_text='Unique hash of the alert labels', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='last_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='occurrence_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
