# Generated by Django 4.2.11 on 2026-01-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_ops', '0004_incident_fingerprint_incident_last_analyzed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='enable_ai_analysis',
            field=models.BooleanField(default=True, help_text='Switch to enable/disable AI analysis. If disabled, uses Prometheus metrics only.'),
        ),
    ]
