# Generated by Django 4.2.11 on 2026-01-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_ops', '0005_aiconfig_enable_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='k8s_events',
            field=models.JSONField(default=list, help_text='K8s Events for frontend display'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='k8s_pod_status',
            field=models.JSONField(default=dict, help_text='Pod status and conditions'),
        ),
    ]
