# Generated by Django 4.2.11 on 2026-03-31 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trafficdashboardconfig',
            options={},
        ),
    ]
