# Generated by Django 4.2.11 on 2026-01-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(help_text='Name of the staff member', max_length=100)),
                ('shift_date', models.DateField(help_text='Date of the shift')),
                ('shift_type', models.CharField(help_text='Type of shift (e.g., Morning, Night)', max_length=50)),
                ('extra_info', models.JSONField(blank=True, default=dict, help_text='Additional JSON data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['-shift_date', 'staff_name'],
            },
        ),
    ]
