# Generated by Django 4.2.11 on 2026-01-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-shift_date', 'start_time'], 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='extra_info',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='shift_type',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='staff_name',
        ),
        migrations.AddField(
            model_name='schedule',
            name='create_time',
            field=models.CharField(blank=True, help_text='Creation Time from source', max_length=50),
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.CharField(default='18:00:00', help_text='End Time', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='rule_id',
            field=models.BigIntegerField(blank=True, help_text='Source Rule ID', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='staff_ids',
            field=models.CharField(blank=True, help_text='Staff IDs string', max_length=255),
        ),
        migrations.AddField(
            model_name='schedule',
            name='staff_list',
            field=models.JSONField(blank=True, default=list, help_text='List of staff info objects'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.CharField(default='09:00:00', help_text='Start Time', max_length=20),
        ),
    ]
