# Generated by Django 4.2.11 on 2026-01-29 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_schedule_options_remove_schedule_extra_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='new', max_length=20)),
                ('action_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('oncall', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processing_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('external_last_action', models.CharField(blank=True, default='', max_length=50)),
                ('external_last_http_status', models.IntegerField(blank=True, null=True)),
                ('external_last_error', models.TextField(blank=True, default='')),
                ('external_last_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneAlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_url', models.CharField(blank=True, default='', max_length=255)),
                ('slack_webhook_url', models.CharField(blank=True, default='', max_length=500)),
                ('external_api_url', models.CharField(blank=True, default='', max_length=500)),
                ('external_api_username', models.CharField(blank=True, default='', max_length=255)),
                ('external_api_password', models.CharField(blank=True, default='', max_length=255)),
                ('incoming_token', models.CharField(blank=True, default='', max_length=255)),
                ('auto_complete_minutes', models.IntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
