# Generated by Django 4.2.11 on 2026-02-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_phonealert_phonealertconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonealertconfig',
            name='oncall_slack_map',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
